name: Publish to NuGet & GitHub Packages

on:
  push:
    tags:
      - 'v*'   # запускається коли пушиш тег, наприклад v1.2.3

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Extract version from tag
      id: get_version
      run: echo "TAG_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Pack NuGet package
      run: dotnet pack -c Release --no-build -o out /p:Version=${TAG_VERSION}

    # - name: Publish to NuGet.org
    #   run: dotnet nuget push "out/*.nupkg" \
    #        --api-key ${{ secrets.NUGET_API_KEY }} \
    #        --source https://api.nuget.org/v3/index.json

    - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ TAG_VERSION }}
          name: Release v${{ TAG_VERSION }}
          files: out/*.nupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    #- name: Publish to GitHub Packages
    #  env:
    #    NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #  run: dotnet nuget push "out/*.nupkg" --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
